//! Memory stays within the worst case (programming-model.md, section 6.3), measured by
//! a counting allocator: the session child domain with every session filled to
//! its limits. Skein tests its generic containers in its own memory world.

use std::mem::size_of;

use skein_lib::{Duration, Env, Queue, Time, Token, Wall};
use skein_world::domain::heap::{self, Meter};
use smith_domain_session::llm::{Block, Completion, Decoded, Descriptor, Endpoint, Failure, Problem, Stop, Usage};
use smith_domain_session::{Budget, Domain, Event, Limits, MAX_PARALLEL, Request, Spec, max_out, worst_case};
use smith_domain_tools::{Authority, Call, Done, Effect, Grants, Name, Part, Path, Repo, Version};
use smith_session_world::{TOOLS, reservation_envelope};

#[global_allocator]
static HEAP: heap::Counting = heap::Counting;

fn bytes(len: u64) -> Box<[u8]> {
    vec![b'x'; usize::try_from(len).expect("a test length fits")].into_boxed_slice()
}

/// The one name the authority and the call use.
fn name() -> Name {
    Name::new(bytes(1)).expect("a name")
}

/// What the session's tools may do: inspect one repository, mounted at a
/// one-byte name.
fn authority() -> Authority {
    Authority {
        cwd: Box::new([name()]),
        repos: Box::new([Repo { mount: Box::new([name()]), root: Token::new(1), writable: false }]),
        grants: Grants { inspect: true, modify: false, shell: false },
        env: Box::new([]),
    }
}

const VERSION: Version = Version::new([1, 0, 0, 0]);

fn size(of: usize) -> u64 {
    u64::try_from(of).expect("a size fits")
}

const LIMITS: Limits = Limits {
    sessions: 1,
    spend: 1,
    messages: 4,
    session_bytes: 1024,
    completion_bytes: 4096,
    completion_blocks: 16,
    failure_bytes: 512,
    delegated_result_bytes: 16_384,
    budget: Budget {
        turns: 16,
        input: 1 << 20,
        output: 1 << 20,
        cache_read: 1 << 20,
        cache_write: 1 << 20,
        time: Duration::from_secs(3600),
    },
    max_tokens: 1024,
    retries: 1,
    backoff_base: Duration::from_secs(60),
    backoff_max: Duration::from_secs(60),
    call_timeout: Duration::from_secs(30),
    tool_timeout: Duration::from_secs(20),
    facts: 64,
    parallel_tools: 1,
    // Reads answer with the whole file loaded.
    tools: smith_domain_tools::Limits { kits: 1, read_bytes: 1 << 20, file_bytes: 1 << 20, ..TOOLS },
};

/// What a step asked for last, without the payload.
enum Asked {
    Complete { owner: Token },
    Io { owner: Token },
    Other,
}

/// How a session fills its bytes.
#[derive(Clone, Copy, Debug)]
enum Route {
    /// The LLM calls a tool, whose output fills the rest.
    Tool,
    /// The LLM makes a call that cannot be decoded, whose problem, and the
    /// answer that repeats it, fill the rest.
    Invalid,
    /// The LLM yields, and the opener's next message fills the rest.
    Talk,
}

/// Source-derived caps for original payload generation; explicit credit and
/// message-cell envelopes replace V1's ignored receiving provisions.
fn pressure_limits(original: Limits, route: Route, messages: u32) -> (Limits, u64, u64, u64) {
    let pressure = original.session_bytes;
    let block = size(size_of::<Block>());
    let part = size(size_of::<Part>());
    let spec_cost = 2 + 2 * size(size_of::<Descriptor>()) + block + 1;
    let tooling_cost = block + 3 + part + 1 + block + 1;
    let output = pressure.checked_sub(spec_cost + tooling_cost).expect("original full Tool payload fits");
    let field =
        pressure.checked_sub(spec_cost + block + 3 + block + 1).expect("original full Invalid payload fits") / 2;
    let completion_bytes = match route {
        Route::Tool => block + 3 + part + 1,
        Route::Invalid => block + 3 + field,
        Route::Talk => block + 1,
    };
    // The original 1MiB provision was never generated by this driver: its
    // actual read payload was exactly `output`. Retain that exact maximum here;
    // a separate refusal control keeps the former 1MiB receiving promise.
    let tools = smith_domain_tools::Limits {
        kits: original.sessions,
        calls: original.parallel_tools.max(original.tools.calls),
        read_bytes: u32::try_from(output).expect("original read maximum fits"),
        ..original.tools
    };
    let mut limits = Limits {
        tools,
        completion_bytes,
        completion_blocks: original.parallel_tools,
        // A second provider turn may contain calls: its assistant and results
        // need two message cells even when the old V1 driver expected one.
        messages: original.messages.max(messages),
        ..original
    };
    let envelope = reservation_envelope(&limits).expect("checked provider and whole-batch bounds");
    limits.session_bytes = pressure.checked_add(envelope).expect("bounded payload plus canonical credit");
    (limits, spec_cost, output, field)
}

/// Observe co-emitted boundary records without replacing an outstanding
/// provider/IO request, then drop receiver-owned payload copies before metering.
fn observe_fill(
    out: &mut Queue<Request>,
    observed: &mut [(bool, u32, u32, u32, bool)],
    full_service: bool,
) -> Option<Asked> {
    let mut asked = None;
    while let Some(request) = out.pop() {
        match request {
            Request::Complete { owner, .. } => {
                assert!(asked.is_none() || matches!(asked, Some(Asked::Other)));
                asked = Some(Asked::Complete { owner });
            }
            Request::Io { owner, .. } => {
                assert!(asked.is_none() || matches!(asked, Some(Asked::Other)));
                asked = Some(Asked::Io { owner });
            }
            Request::Opened { opener, .. } => {
                let row = &mut observed[usize::try_from(opener.raw()).expect("bounded opener")];
                assert!(!row.0, "one opening per original full-payload fixture");
                row.0 = true;
            }
            Request::Used { opener, usage } => {
                assert_eq!(usage, Usage::ZERO);
                observed[usize::try_from(opener.raw()).expect("bounded opener")].1 += 1;
            }
            Request::Turn { opener, turn } => {
                let row = &mut observed[usize::try_from(opener.raw()).expect("bounded opener")];
                row.2 += 1;
                assert_eq!(
                    (turn.version, turn.endpoint, turn.dialect, turn.sequence),
                    (smith_domain_session::record::VERSION, Endpoint(0), 2, row.2)
                );
                assert_eq!((turn.usage, turn.spent), (Usage::ZERO, 0));
                assert_eq!(row.1, row.2, "every actual accepted completion emits concrete history");
                for message in &turn.messages {
                    for block in &message.content {
                        if let Block::ToolCall { call, .. } = block {
                            assert_eq!(*call, Decoded::Historical, "emitted copies retain no live authority");
                        }
                    }
                }
            }
            Request::Priced { opener, spent, own_spent } => {
                assert_eq!((spent, own_spent), (0, 0));
                observed[usize::try_from(opener.raw()).expect("bounded opener")].3 += 1;
            }
            Request::Yielded { .. } => {
                if asked.is_none() {
                    asked = Some(Asked::Other);
                }
            }
            Request::Ended { opener, end, turns, usage } => {
                assert!(full_service, "admissible original payload must enter backoff");
                assert_eq!((end, turns, usage), (smith_domain_session::End::TranscriptFull, 2, Usage::ZERO));
                let row = &mut observed[usize::try_from(opener.raw()).expect("bounded opener")];
                assert!(!row.4, "one exact-full terminal");
                row.4 = true;
                if asked.is_none() {
                    asked = Some(Asked::Other);
                }
            }
            Request::Cancel { .. } | Request::CancelIo { .. } | Request::Delegate { .. } | Request::Withdraw { .. } => {
                panic!("the maximum-payload driver has no other terminal rights")
            }
        }
    }
    asked
}

/// Preserve each original exact payload pressure and fill route, with an explicit
/// canonical receiving-credit envelope. Each pressure case enters backoff
/// holding its original full payload and both alarms; a separate control below
/// fills the maximum payload that can still fund the next provider credit. Credits reserve
/// space without allocating; emitted concrete Turn/prompt/yield copies belong to
/// their receivers and are dropped under the shared meter's handoff convention.
fn fill(original: Limits, route: Route, full_service: bool) {
    let pressure = original.session_bytes;
    let block = size(size_of::<Block>());
    // Each original route reaches three held messages; the full-service
    // supplement adds one assistant and one caller message. Two more cells
    // must remain for the provider's next assistant and possible results.
    let held_messages = 3_u32.checked_add(if full_service { 2 } else { 0 }).expect("bounded story messages");
    let messages = held_messages.checked_add(2).expect("checked provider message-cell reserve");
    let (limits, spec_cost, output, field) = pressure_limits(original, route, messages);
    let bound = worst_case(&limits).expect("the test limits fit");
    let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
    let mut out = Queue::with_capacity(max_out(&limits));
    let count = usize::try_from(limits.sessions).expect("bounded session count");
    let mut observed = vec![(false, 0_u32, 0_u32, 0_u32, false); count];
    let meter = Meter::new();
    let mut domain = Domain::new(&limits, 1);
    let mut step = |event: Event| -> Option<Asked> {
        let may_rest = matches!(route, Route::Invalid) && matches!(event, Event::Completed { .. });
        meter.start();
        smith_domain_session::step(&mut domain, &env, event, &mut out);
        let measured = meter.end();
        let mut asked = observe_fill(&mut out, &mut observed, full_service);
        meter.check(measured, bound, &limits);
        if may_rest {
            domain.reclaim();
        }
        if domain.is_ready() {
            meter.start();
            smith_domain_session::resume(&mut domain, &env, &mut out);
            let measured = meter.end();
            asked = observe_fill(&mut out, &mut observed, full_service).or(asked);
            meter.check(measured, bound, &limits);
        }
        asked
    };
    for opener in 0..limits.sessions {
        let opener = Token::new(u64::from(opener));
        let Some(Asked::Complete { owner }) = step(Event::Open { opener, opening: zero_opening(fill_spec(limits)) })
        else {
            panic!("the original spec and explicit canonical credit fit");
        };
        match route {
            Route::Tool => {
                let path = Path { absolute: false, parts: Box::new([Part::Name { name: name() }]) };
                let call = Decoded::Owned { call: Call::Read { path, skip: 0, lines: None } };
                let content =
                    Box::new([Block::ToolCall { id: bytes(1), name: bytes(1), input: bytes(1), call, replay: None }]);
                let completion = Completion { content, stop: Stop::ToolUse, usage: Usage::ZERO };
                let Some(Asked::Io { owner: op }) = step(Event::Completed { owner, completion }) else {
                    panic!("the original maximum read has full reserved receiving space");
                };
                let Some(Asked::Complete { .. }) =
                    step(Event::Done { owner: op, done: Done::Loaded { content: bytes(output), version: VERSION } })
                else {
                    panic!("original exact-payload result leaves canonical provider credit");
                };
            }
            Route::Invalid => {
                let call = Decoded::Invalid { problem: Problem::Missing { field: bytes(field) } };
                let content =
                    Box::new([Block::ToolCall { id: bytes(1), name: bytes(1), input: bytes(1), call, replay: None }]);
                let completion = Completion { content, stop: Stop::ToolUse, usage: Usage::ZERO };
                let Some(Asked::Complete { .. }) = step(Event::Completed { owner, completion }) else {
                    panic!("the original maximum problem and exact repeated answer fit");
                };
            }
            Route::Talk => {
                let message = pressure - spec_cost - (block + 1) - block;
                let content = Box::new([Block::Text { text: bytes(1), replay: None }]);
                let completion = Completion { content, stop: Stop::EndTurn, usage: Usage::ZERO };
                let Some(Asked::Other) = step(Event::Completed { owner, completion }) else {
                    panic!("the original one-byte answer yields");
                };
                let Some(Asked::Complete { .. }) = step(Event::Continue { session: owner, content: bytes(message) })
                else {
                    panic!("original exact-payload continuation leaves canonical provider credit");
                };
            }
        }
        if full_service {
            fill_service_tail(&mut step, &limits, route, owner, pressure, (spec_cost, field));
        } else {
            assert!(
                step(Event::Failed {
                    owner,
                    failure: Failure::Overloaded,
                    evidence: smith_domain_session::llm::Evidence::Unknown,
                    detail: Box::default()
                })
                .is_none(),
                "the original maximum generated payload backs off with both alarms"
            );
        }
    }
    let turns = if full_service { 2 } else { 1 };
    assert!(observed.iter().all(|&(opened, used, recorded, priced, ended)| opened
        && used == turns
        && recorded == turns
        && priced >= turns
        && ended == full_service));
    assert_retained_payload(&meter, &limits, route, full_service, pressure);
}

fn assert_retained_payload(meter: &Meter, limits: &Limits, route: Route, full_service: bool, pressure: u64) {
    let payload = if full_service { limits.session_bytes } else { pressure };
    // An all-invalid batch resumes after reclaim, so full-service terminal
    // payloads of different sessions do not coexist.
    let simultaneous = if full_service && matches!(route, Route::Invalid) { 1 } else { limits.sessions };
    assert!(
        meter.held() >= u64::from(simultaneous) * payload,
        "{route:?}, full_service={full_service}, {limits:?}: held {} below target {}",
        meter.held(),
        u64::from(simultaneous) * payload
    );
}

/// Supplement every original allocation route by filling the entire service
/// byte cap, with provider/continue handoffs and independent message room.
fn fill_service_tail(
    step: &mut impl FnMut(Event) -> Option<Asked>,
    limits: &Limits,
    route: Route,
    owner: Token,
    pressure: u64,
    charges: (u64, u64),
) {
    let block = size(size_of::<Block>());
    // The original route's full pressure is retained, then an accepted
    // one-byte text answer yields. A final caller-owned continuation
    // fills every remaining byte of the provisioned service envelope.
    // Its next effect is refused before work, independently of message
    // room. This supplements rather than replaces the backoff maximum.
    let content = Box::new([Block::Text { text: bytes(1), replay: None }]);
    assert!(
        matches!(
            step(Event::Completed {
                owner,
                completion: Completion { content, stop: Stop::EndTurn, usage: Usage::ZERO }
            }),
            Some(Asked::Other)
        ),
        "the full-pressure history yields before final padding"
    );
    let retained = match route {
        Route::Tool | Route::Talk => pressure,
        Route::Invalid => charges.0 + block + 3 + block + 1 + 2 * charges.1,
    };
    let held_messages = 3_u32 + 1 + 1;
    assert!(
        limits.messages.checked_sub(held_messages).expect("counted actual held messages") >= 2,
        "exact byte refusal has room for next assistant and result messages"
    );
    let padding = limits
        .session_bytes
        .checked_sub(retained + block + 1 + block)
        .expect("full service can hold its final caller message");
    assert!(
        matches!(step(Event::Continue { session: owner, content: bytes(padding) }), Some(Asked::Other)),
        "the exact full service refuses its next provider effect"
    );
}

fn zero_opening(spec: Spec) -> Box<smith_domain_session::record::Opening> {
    Box::new(smith_domain_session::record::Opening {
        spec,
        dialect: 2,
        prices: smith_domain_session::record::Prices { input: 0, cached: 0, output: 0, unit: 1 },
        budget: 1,
        transcript: None,
        answered: Box::default(),
    })
}

/// Caller-owned input with the same exact byte charge in every fill route.
fn fill_spec(limits: Limits) -> Spec {
    Spec {
        endpoint: Endpoint(0),
        model: bytes(1),
        system: bytes(1),
        authority: authority(),
        delegated: Box::new([
            Descriptor { ticket: Token::new(1), effect: Effect::Write },
            Descriptor { ticket: Token::new(2), effect: Effect::Read },
        ]),
        prompt: bytes(1),
        max_tokens: 1,
        budget: limits.budget,
    }
}

#[test]
fn a_domain_with_every_session_full_stays_within_its_worst_case() {
    for route in [Route::Tool, Route::Invalid, Route::Talk] {
        for full_service in [false, true] {
            fill(LIMITS, route, full_service);
            fill(Limits { sessions: 64, spend: 1, session_bytes: 65_536, ..LIMITS }, route, full_service);
            fill(Limits { sessions: 1000, spend: 1, messages: 8, session_bytes: 600, ..LIMITS }, route, full_service);
            fill(Limits { sessions: 64, spend: 1, parallel_tools: MAX_PARALLEL, ..LIMITS }, route, full_service);
        }
    }
}

#[test]
fn recorded_delegated_turns_hold_exactly_the_byte_cap_and_count_their_copies() {
    use smith_domain_session::record;
    let block = size(size_of::<Block>());
    let spec_charge = 2 + size(size_of::<Descriptor>()) + block + 1;
    let turn_charge = block + 1 + block + 3 + block + 1;
    let output = 16_384 - spec_charge - turn_charge;
    let limits = Limits {
        messages: 6,
        spend: u64::MAX,
        session_bytes: 16_384,
        completion_bytes: 512,
        completion_blocks: 2,
        delegated_result_bytes: output,
        ..LIMITS
    };
    let bound = worst_case(&limits).expect("the counted scenario fits");
    let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
    let mut out = Queue::with_capacity(max_out(&limits));
    let meter = Meter::new();
    let mut domain = Domain::new(&limits, 77);
    let mut saved = Vec::new();
    let mut ended = None;
    let mut drive = |event| {
        meter.start();
        smith_domain_session::step(&mut domain, &env, event, &mut out);
        let measured = meter.end();
        let mut completion = None;
        let mut delegate = None;
        while let Some(request) = out.pop() {
            match request {
                Request::Complete { owner, .. } => completion = Some(owner),
                Request::Delegate { owner, .. } => delegate = Some(owner),
                Request::Turn { turn, .. } => saved.push(turn),
                Request::Priced { spent, own_spent, .. } => {
                    assert_eq!((spent, own_spent), (0, 0));
                }
                Request::Ended { end, .. } => ended = Some(end),
                Request::Opened { .. }
                | Request::Yielded { .. }
                | Request::Used { .. }
                | Request::Cancel { .. }
                | Request::Io { .. }
                | Request::CancelIo { .. }
                | Request::Withdraw { .. } => {}
            }
        }
        meter.check(measured, bound, &limits);
        (completion, delegate)
    };
    let spec = Spec {
        endpoint: Endpoint(7),
        model: bytes(1),
        system: bytes(1),
        authority: authority(),
        delegated: Box::new([Descriptor { ticket: Token::new(2), effect: Effect::Write }]),
        prompt: bytes(1),
        max_tokens: 1,
        budget: limits.budget,
    };
    let (owner, _) = drive(Event::Open {
        opener: Token::new(1),
        opening: Box::new(record::Opening {
            spec,
            dialect: 2,
            prices: record::Prices { input: 1, cached: 1, output: 1, unit: 1 },
            budget: 1,
            transcript: None,
            answered: Box::default(),
        }),
    });
    let (_, delegate) = drive(Event::Completed {
        owner: owner.expect("the counted scenario fits"),
        completion: Completion {
            content: Box::new([
                Block::Opaque { bytes: bytes(1) },
                Block::ToolCall {
                    id: bytes(1),
                    name: bytes(1),
                    input: bytes(1),
                    call: Decoded::Delegated { ticket: Token::new(99), effect: Effect::Write },
                    replay: None,
                },
            ]),
            stop: Stop::ToolUse,
            usage: Usage::ZERO,
        },
    });
    let (owner, _) = drive(Event::Answered {
        owner: delegate.expect("the counted scenario fits"),
        text: bytes(output),
        error: false,
        spent: 0,
    });
    assert!(owner.is_none(), "full actual result is retained; next provider reserve fails before work");
    assert_eq!(ended, Some(smith_domain_session::End::TranscriptFull));
    assert_eq!(saved.len(), 1, "actual full-cap Turn was handed off before Ended");
    assert!(matches!(&saved[0].messages[2].content[0], Block::ToolResult {
        result: smith_domain_session::llm::Returned::Text { text, error: false, replay: None }, ..
    } if text.len() == usize::try_from(output).expect("bounded cap")));
    drop(saved);
    assert!(meter.held() >= limits.session_bytes);
}

#[test]
fn restoring_a_maximum_recorded_history_stays_within_the_counted_bound() {
    use smith_domain_session::record;
    let limits = Limits {
        messages: 6,
        spend: u64::MAX,
        session_bytes: 16_384,
        completion_bytes: 256,
        completion_blocks: 1,
        ..LIMITS
    };
    let bound = worst_case(&limits).expect("the limits fit");
    let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
    let mut out = Queue::with_capacity(max_out(&limits));
    let meter = Meter::new();
    let mut domain = Domain::new(&limits, 78);
    let block = size(size_of::<Block>());
    let charge = 2 + size(size_of::<Descriptor>()) + block + 1;
    let reserve = smith_domain_session::completion_reserve(&limits).expect("complete receiving credit");
    let opaque = limits.session_bytes - charge - 2 * block - 1 - reserve;
    let spec = Spec {
        endpoint: Endpoint(7),
        model: bytes(1),
        system: bytes(1),
        authority: authority(),
        delegated: Box::new([Descriptor { ticket: Token::new(2), effect: Effect::Write }]),
        prompt: bytes(1),
        max_tokens: 1,
        budget: limits.budget,
    };
    let history = record::Transcript {
        version: record::VERSION,
        endpoint: Endpoint(7),
        dialect: 2,
        turns: Box::new([record::Turn {
            version: record::VERSION,
            endpoint: Endpoint(7),
            dialect: 2,
            sequence: 1,
            usage: Usage::ZERO,
            spent: 0,
            messages: Box::new([
                smith_domain_session::llm::Message {
                    role: smith_domain_session::llm::Role::User,
                    content: Box::new([Block::Text { text: bytes(1), replay: None }]),
                },
                smith_domain_session::llm::Message {
                    role: smith_domain_session::llm::Role::Assistant,
                    content: Box::new([Block::Opaque { bytes: bytes(opaque) }]),
                },
            ]),
        }]),
    };
    meter.start();
    smith_domain_session::step(
        &mut domain,
        &env,
        Event::Open {
            opener: Token::new(1),
            opening: Box::new(record::Opening {
                spec,
                dialect: 2,
                prices: record::Prices { input: 1, cached: 1, output: 1, unit: 1 },
                budget: 1,
                transcript: Some(history),
                answered: Box::default(),
            }),
        },
        &mut out,
    );
    let measured = meter.end();
    let mut completed = false;
    while let Some(request) = out.pop() {
        if let Request::Complete { .. } = request {
            completed = true;
        }
    }
    assert!(completed, "maximum admitted history separately preserves complete provider receiving room");
    meter.check(measured, bound, &limits);
    assert!(meter.held() >= limits.session_bytes - reserve);
}

#[test]
fn an_oversized_waking_result_tail_is_refused_before_cloning_provider_ids() {
    use smith_domain_session::{
        llm::{Message, Role},
        record,
    };
    let tools = restore_tail_tools();
    let calls = 128_u32;
    let id_bytes = 8192_u64;
    let block = size(size_of::<Block>());
    let spec_charge = 2 + size(size_of::<Descriptor>()) + block + 1;
    let original = block + 1 + u64::from(calls) * (block + id_bytes + 2);
    let limits = Limits { messages: 4, session_bytes: spec_charge + original, spend: u64::MAX, tools, ..LIMITS };
    let bound = worst_case(&limits).expect("bounded restore limits");
    let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
    let mut out = Queue::with_capacity(max_out(&limits));
    let meter = Meter::new();
    let mut domain = Domain::new(&limits, 79);
    let mut tail = Vec::new();
    for call in 0..calls {
        let mut id = bytes(id_bytes).into_vec();
        id[..4].copy_from_slice(&call.to_le_bytes());
        tail.push(Block::ToolCall {
            id: id.into(),
            name: bytes(1),
            input: bytes(1),
            call: Decoded::Historical,
            replay: None,
        });
    }
    let history = record::Transcript {
        version: record::VERSION,
        endpoint: Endpoint(7),
        dialect: 2,
        turns: Box::new([record::Turn {
            version: record::VERSION,
            endpoint: Endpoint(7),
            dialect: 2,
            sequence: 1,
            usage: Usage::ZERO,
            spent: 0,
            messages: Box::new([
                Message { role: Role::User, content: Box::new([Block::Text { text: bytes(1), replay: None }]) },
                Message { role: Role::Assistant, content: tail.into() },
            ]),
        }]),
    };
    let spec = Spec {
        endpoint: Endpoint(7),
        model: bytes(1),
        system: bytes(1),
        authority: authority(),
        delegated: Box::new([Descriptor { ticket: Token::new(2), effect: Effect::Write }]),
        prompt: bytes(1),
        max_tokens: 1,
        budget: limits.budget,
    };
    meter.start();
    smith_domain_session::step(
        &mut domain,
        &env,
        Event::Open {
            opener: Token::new(1),
            opening: Box::new(record::Opening {
                spec,
                dialect: 2,
                prices: record::Prices { input: 1, cached: 1, output: 1, unit: 1 },
                budget: 1,
                transcript: Some(history),
                answered: Box::default(),
            }),
        },
        &mut out,
    );
    let measured = meter.end();
    assert_eq!(
        out.pop(),
        Some(Request::Ended {
            opener: Token::new(1),
            end: smith_domain_session::End::TranscriptRefused { reason: record::Refusal::TooLarge },
            turns: 0,
            usage: Usage::ZERO,
        })
    );
    assert!(out.is_empty());
    meter.check(measured, bound, &limits);
    domain.reclaim();
    assert_eq!(domain.sessions(), 0);
    assert_eq!(domain.kits(), 0);
}

/// Minimal lower inventory isolates the large historical-ID staging peak.
fn restore_tail_tools() -> smith_domain_tools::Limits {
    smith_domain_tools::Limits {
        kits: 1,
        calls: 1,
        path_bytes: 16,
        known_files: 0,
        file_bytes: 16,
        read_bytes: 16,
        list_entries: 1,
        list_bytes: 4096,
        match_lines: 1,
        env_bytes: 0,
        shell_head: 0,
        shell_tail: 0,
        search_hits: 1,
        search_bytes: 16,
        facts: 0,
        ..LIMITS.tools
    }
}

/// Heap-free observations so handoff payloads can be dropped and costed before
/// the shared meter checks the domain's own peak.
#[derive(Default)]
struct MemorySeen {
    complete: Option<Token>,
    io: [Option<Token>; MAX_PARALLEL as usize],
    io_count: usize,
    used: u32,
    turns: u32,
    priced: u32,
    yielded: u32,
    end: Option<smith_domain_session::End>,
    read: Option<u64>,
    not_run: u32,
}

fn memory_seen(out: &mut Queue<Request>) -> MemorySeen {
    let mut seen = MemorySeen::default();
    while let Some(request) = out.pop() {
        match request {
            Request::Complete { owner, .. } => assert!(seen.complete.replace(owner).is_none()),
            Request::Io { owner, .. } => {
                seen.io[seen.io_count] = Some(owner);
                seen.io_count += 1;
            }
            Request::Opened { .. } => {}
            Request::Used { usage, .. } => {
                assert_eq!(usage, Usage::ZERO);
                seen.used += 1;
            }
            Request::Turn { turn, .. } => {
                assert_eq!(
                    (turn.version, turn.endpoint, turn.dialect),
                    (smith_domain_session::record::VERSION, Endpoint(0), 2)
                );
                assert_eq!((turn.usage, turn.spent), (Usage::ZERO, 0));
                for message in &turn.messages {
                    for block in &message.content {
                        match block {
                            Block::ToolCall { call, .. } => assert_eq!(*call, Decoded::Historical),
                            Block::ToolResult {
                                result:
                                    smith_domain_session::llm::Returned::Owned {
                                        outcome: smith_domain_tools::Outcome::Read { content, .. },
                                    },
                                ..
                            } => {
                                seen.read = Some(size(content.len()));
                            }
                            Block::ToolResult { result: smith_domain_session::llm::Returned::NotRun, .. } => {
                                seen.not_run += 1;
                            }
                            Block::ToolResult { .. }
                            | Block::Text { .. }
                            | Block::Refusal { .. }
                            | Block::Opaque { .. } => {}
                        }
                    }
                }
                seen.turns += 1;
            }
            Request::Priced { spent, own_spent, .. } => {
                assert_eq!((spent, own_spent), (0, 0));
                seen.priced += 1;
            }
            Request::Yielded { .. } => seen.yielded += 1,
            Request::Ended { end, usage, .. } => {
                assert_eq!(usage, Usage::ZERO);
                assert!(seen.end.replace(end).is_none());
            }
            Request::Cancel { .. } | Request::CancelIo { .. } | Request::Delegate { .. } | Request::Withdraw { .. } => {
                panic!("the measured owned-provider controls have no other terminal rights")
            }
        }
    }
    seen
}

fn measured_step(
    domain: &mut Domain,
    env: &Env<Limits>,
    out: &mut Queue<Request>,
    meter: &Meter,
    bound: u64,
    event: Event,
) -> MemorySeen {
    meter.start();
    smith_domain_session::step(domain, env, event, out);
    let measured = meter.end();
    let seen = memory_seen(out);
    meter.check(measured, bound, &env.limits);
    seen
}

fn measured_resume(
    domain: &mut Domain,
    env: &Env<Limits>,
    out: &mut Queue<Request>,
    meter: &Meter,
    bound: u64,
) -> MemorySeen {
    assert!(domain.is_ready());
    meter.start();
    smith_domain_session::resume(domain, env, out);
    let measured = meter.end();
    let seen = memory_seen(out);
    meter.check(measured, bound, &env.limits);
    seen
}

fn read_completion(width: u32) -> Completion {
    let mut blocks = Vec::with_capacity(usize::try_from(width).expect("bounded width"));
    for number in 0..width {
        blocks.push(Block::ToolCall {
            id: Box::new([b'a' + u8::try_from(number).expect("at most eight")]),
            name: bytes(1),
            input: bytes(1),
            replay: None,
            call: Decoded::Owned {
                call: Call::Read {
                    path: Path { absolute: false, parts: Box::new([Part::Name { name: name() }]) },
                    skip: 0,
                    lines: None,
                },
            },
        });
    }
    Completion { content: blocks.into_boxed_slice(), stop: Stop::ToolUse, usage: Usage::ZERO }
}

#[test]
fn provider_admission_and_owned_result_space_have_exact_and_one_short_controls() {
    let block = size(size_of::<Block>());
    let spec_cost = 2 + 2 * size(size_of::<Descriptor>()) + block + 1;
    let completion_bytes = block + 3 + size(size_of::<Part>()) + 1;
    let base = Limits { completion_bytes, completion_blocks: 1, failure_bytes: 0, messages: 5, ..LIMITS };
    let reserve = smith_domain_session::completion_reserve(&base).expect("checked minimal actual provider terminal");
    let exact = spec_cost.checked_add(reserve).expect("checked spec plus provider reserve");
    for session_bytes in [exact - 1, exact] {
        let limits = Limits { session_bytes, ..base };
        let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
        let mut out = Queue::with_capacity(max_out(&limits));
        let meter = Meter::new();
        let mut domain = Domain::new(&limits, 11);
        let seen = measured_step(
            &mut domain,
            &env,
            &mut out,
            &meter,
            worst_case(&limits).expect("checked limits"),
            Event::Open { opener: Token::new(1), opening: zero_opening(fill_spec(limits)) },
        );
        if session_bytes == exact {
            assert!(seen.complete.is_some(), "exact provider reservation admits work");
        } else {
            assert!(seen.complete.is_none());
            assert_eq!(
                seen.end,
                Some(smith_domain_session::End::TranscriptRefused {
                    reason: smith_domain_session::record::Refusal::TooLarge
                })
            );
            assert_eq!((domain.sessions(), domain.kits()), (0, 0), "one short refuses before any child effects");
        }
    }
    let skeleton = spec_cost + completion_bytes + block + 1;
    let exact_result = exact.checked_sub(skeleton).expect("minimal provider reserve leaves actual result room");
    for read_bytes in [exact_result, exact_result + 1, 1 << 20] {
        let limits = Limits {
            session_bytes: exact,
            tools: smith_domain_tools::Limits {
                read_bytes: u32::try_from(read_bytes).expect("bounded read cap"),
                ..base.tools
            },
            ..base
        };
        let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
        let mut out = Queue::with_capacity(max_out(&limits));
        let meter = Meter::new();
        let mut domain = Domain::new(&limits, 12);
        let bound = worst_case(&limits).expect("checked limits");
        let seen = measured_step(
            &mut domain,
            &env,
            &mut out,
            &meter,
            bound,
            Event::Open { opener: Token::new(1), opening: zero_opening(fill_spec(limits)) },
        );
        let owner = seen.complete.expect("spec plus exact provider credit admits");
        let seen = measured_step(
            &mut domain,
            &env,
            &mut out,
            &meter,
            bound,
            Event::Completed { owner, completion: read_completion(1) },
        );
        if read_bytes == exact_result {
            assert_eq!(seen.io_count, 1, "exact promised result space starts its IO effect");
            let seen = measured_step(
                &mut domain,
                &env,
                &mut out,
                &meter,
                bound,
                Event::Done {
                    owner: seen.io[0].expect("actual IO right"),
                    done: Done::Loaded { content: bytes(exact_result), version: VERSION },
                },
            );
            assert_eq!(
                (seen.turns, seen.read),
                (1, Some(exact_result)),
                "actual exact-full result is emitted concretely"
            );
            assert_eq!(seen.end, Some(smith_domain_session::End::TranscriptFull));
            assert!(seen.complete.is_none(), "full actual terminal prevents the next provider effect");
            assert!(meter.held() >= exact, "full concrete transcript remains retained before reclaim");
        } else {
            assert_eq!(seen.io_count, 0, "one-short and former1MiB receiving promises refuse before IO");
            assert_eq!((seen.turns, seen.not_run), (1, 1));
            assert_eq!(seen.end, Some(smith_domain_session::End::TranscriptFull));
        }
    }
}

#[test]
fn maximum_admissible_backoff_preserves_the_exact_next_provider_credit() {
    let original = Limits { sessions: 1, session_bytes: 600, messages: 8, ..LIMITS };
    let (limits, spec_cost, _, _) = pressure_limits(original, Route::Talk, 3_u32 + 2);
    let reserve = smith_domain_session::completion_reserve(&limits).expect("checked credit");
    let held = limits.session_bytes.checked_sub(reserve).expect("retained maximum leaves exact provider credit");
    let block = size(size_of::<Block>());
    let message = held.checked_sub(spec_cost + block + 1 + block).expect("maximum caller message fits");
    let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
    let mut out = Queue::with_capacity(max_out(&limits));
    let meter = Meter::new();
    let mut domain = Domain::new(&limits, 13);
    let bound = worst_case(&limits).expect("checked limits");
    let seen = measured_step(
        &mut domain,
        &env,
        &mut out,
        &meter,
        bound,
        Event::Open { opener: Token::new(1), opening: zero_opening(fill_spec(limits)) },
    );
    let owner = seen.complete.expect("initial provider credit fits");
    let seen = measured_step(
        &mut domain,
        &env,
        &mut out,
        &meter,
        bound,
        Event::Completed {
            owner,
            completion: Completion {
                content: Box::new([Block::Text { text: bytes(1), replay: None }]),
                stop: Stop::EndTurn,
                usage: Usage::ZERO,
            },
        },
    );
    assert_eq!((seen.used, seen.turns, seen.yielded), (1, 1, 1));
    let seen = measured_step(
        &mut domain,
        &env,
        &mut out,
        &meter,
        bound,
        Event::Continue { session: owner, content: bytes(message) },
    );
    assert_eq!(seen.complete, Some(owner), "held payload plus receiving credit exactly equals service cap");
    assert_eq!(spec_cost + block + 1 + block + message + reserve, limits.session_bytes);
    let seen = measured_step(
        &mut domain,
        &env,
        &mut out,
        &meter,
        bound,
        Event::Failed {
            owner,
            failure: Failure::Overloaded,
            evidence: smith_domain_session::llm::Evidence::Unknown,
            detail: Box::default(),
        },
    );
    assert!(seen.complete.is_none() && seen.end.is_none(), "maximum admitted payload backs off rather than ending");
    assert!(domain.next_deadline().is_some(), "retry and session alarms remain live");
    assert!(meter.held() >= held, "maximum admissible backoff retains its full concrete payload");
}

#[test]
fn the_original_maximum_parallel_width_has_live_result_rights() {
    let width = MAX_PARALLEL;
    let call = size(size_of::<Block>()) + 3 + size(size_of::<Part>()) + 1;
    let mut limits = Limits {
        messages: 5,
        parallel_tools: width,
        completion_blocks: width,
        completion_bytes: call * u64::from(width),
        tools: smith_domain_tools::Limits { calls: width, read_bytes: 4096, ..LIMITS.tools },
        ..LIMITS
    };
    limits.session_bytes = limits
        .session_bytes
        .checked_add(reservation_envelope(&limits).expect("checked widest credit"))
        .expect("pressure plus credit fits");
    let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
    let mut out = Queue::with_capacity(max_out(&limits));
    let meter = Meter::new();
    let mut domain = Domain::new(&limits, 14);
    let bound = worst_case(&limits).expect("checked limits");
    let seen = measured_step(
        &mut domain,
        &env,
        &mut out,
        &meter,
        bound,
        Event::Open { opener: Token::new(1), opening: zero_opening(fill_spec(limits)) },
    );
    let owner = seen.complete.expect("widest provider credit fits");
    let seen = measured_step(
        &mut domain,
        &env,
        &mut out,
        &meter,
        bound,
        Event::Completed { owner, completion: read_completion(width) },
    );
    assert_eq!(seen.io_count, usize::try_from(width).expect("bounded width"));
    assert_eq!(domain.runs(), width, "all eight actual owned rights coexist before any terminal");
    let rights = seen.io;
    let mut turns = 0;
    for right in rights {
        let seen = measured_step(
            &mut domain,
            &env,
            &mut out,
            &meter,
            bound,
            Event::Done {
                owner: right.expect("each maximum-width slot owns its IO terminal"),
                done: Done::Loaded { content: bytes(4096), version: VERSION },
            },
        );
        turns += seen.turns;
    }
    assert_eq!(turns, 1, "the widest batch emits one concrete settled Turn");
    assert_eq!(domain.runs(), width, "ended runs remain present until the reclaim point");
}

#[test]
fn the_original_four_message_cap_refuses_the_next_provider_before_work() {
    let original = Limits { messages: 4, ..LIMITS };
    for route in [Route::Tool, Route::Invalid, Route::Talk] {
        let (mut limits, _, output, field) = pressure_limits(original, route, original.messages);
        limits.messages = original.messages;
        assert_eq!(limits.messages - 3, 1, "the original held transcript leaves one cell, below the two-cell promise");
        let env = Env { now: Time::ZERO, wall: Wall::EPOCH, limits };
        let mut out = Queue::with_capacity(max_out(&limits));
        let meter = Meter::new();
        let mut domain = Domain::new(&limits, 15);
        let bound = worst_case(&limits).expect("checked original message cap");
        let seen = measured_step(
            &mut domain,
            &env,
            &mut out,
            &meter,
            bound,
            Event::Open { opener: Token::new(1), opening: zero_opening(fill_spec(limits)) },
        );
        let owner = seen.complete.expect("initial original message count admits");
        let seen = match route {
            Route::Tool => {
                let seen = measured_step(
                    &mut domain,
                    &env,
                    &mut out,
                    &meter,
                    bound,
                    Event::Completed { owner, completion: read_completion(1) },
                );
                let op = seen.io[0].expect("original full generated read admits its IO right");
                measured_step(
                    &mut domain,
                    &env,
                    &mut out,
                    &meter,
                    bound,
                    Event::Done { owner: op, done: Done::Loaded { content: bytes(output), version: VERSION } },
                )
            }
            Route::Invalid => {
                let seen = measured_step(
                    &mut domain,
                    &env,
                    &mut out,
                    &meter,
                    bound,
                    Event::Completed {
                        owner,
                        completion: Completion {
                            content: Box::new([Block::ToolCall {
                                id: bytes(1),
                                name: bytes(1),
                                input: bytes(1),
                                replay: None,
                                call: Decoded::Invalid { problem: Problem::Missing { field: bytes(field) } },
                            }]),
                            stop: Stop::ToolUse,
                            usage: Usage::ZERO,
                        },
                    },
                );
                assert!(seen.complete.is_none() && seen.end.is_none());
                domain.reclaim();
                measured_resume(&mut domain, &env, &mut out, &meter, bound)
            }
            Route::Talk => {
                let block = size(size_of::<Block>());
                let spec_cost = 2 + 2 * size(size_of::<Descriptor>()) + block + 1;
                let message = original.session_bytes - spec_cost - block - 1 - block;
                let seen = measured_step(
                    &mut domain,
                    &env,
                    &mut out,
                    &meter,
                    bound,
                    Event::Completed {
                        owner,
                        completion: Completion {
                            content: Box::new([Block::Text { text: bytes(1), replay: None }]),
                            stop: Stop::EndTurn,
                            usage: Usage::ZERO,
                        },
                    },
                );
                assert_eq!((seen.used, seen.turns, seen.yielded), (1, 1, 1));
                measured_step(
                    &mut domain,
                    &env,
                    &mut out,
                    &meter,
                    bound,
                    Event::Continue { session: owner, content: bytes(message) },
                )
            }
        };
        assert!(seen.complete.is_none(), "original one-cell remainder never starts another provider effect");
        assert_eq!(seen.end, Some(smith_domain_session::End::TranscriptFull));
    }
}
