[package]
name = "smith-local-service"
description = "Local host composition for Smith"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
skein-lib.workspace = true
skein-io.workspace = true
smith-domain.workspace = true
smith-agent-service.workspace = true
smith-local-domain.workspace = true
smith-local-protocol.workspace = true
smith-host-domain.workspace = true
smith-host-protocol.workspace = true
smith-protocol-channel.workspace = true
smith-transcript.workspace = true

[dev-dependencies]
skein-fake-peers.workspace = true
skein-world.workspace = true
skein-tls-world.workspace = true
skein-sim.workspace = true
skein-fake-machine.workspace = true
smith-agent-world.workspace = true
smith-agent-process-world.workspace = true
smith-host-world.workspace = true

[lints]
workspace = true
